// <auto-generated />
using System;
using Kart.User.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kart.User.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260726024557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kart.User.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line1");

                    b.Property<string>("Line2")
                        .HasColumnType("text")
                        .HasColumnName("line2");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_addresses_user_id");

                    b.HasIndex("UserId", "Type")
                        .IsUnique()
                        .HasDatabaseName("idx_addresses_one_default_per_type")
                        .HasFilter("is_default");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Kart.User.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProjectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "idx_user_outbox_unprojected")
                        .HasFilter("projected_at IS NULL");

                    b.HasIndex(new[] { "Id" }, "idx_user_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("user_outbox_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_outbox_events_event_type", "event_type IN ('UserProfileUpdated', 'UserNotificationPreferenceUpdated', 'UserDataErased', 'UserReadModelProjectionRequested')");
                        });
                });

            modelBuilder.Entity("Kart.User.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<bool>("AppInstalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("app_installed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ErasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erased_at");

                    b.Property<string>("ErasureStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("erasure_status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Kart.User.Domain.Entities.Address", b =>
                {
                    b.HasOne("Kart.User.Domain.Entities.UserProfile", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kart.User.Domain.Entities.UserProfile", b =>
                {
                    b.OwnsOne("Kart.User.Domain.ValueObjects.IdentityContactCopy", "ContactCopy", b1 =>
                        {
                            b1.Property<string>("UserProfileUserId")
                                .HasColumnType("text");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("text")
                                .HasColumnName("display_name_copy");

                            b1.Property<string>("Email")
                                .HasColumnType("text")
                                .HasColumnName("email_copy");

                            b1.Property<DateTimeOffset?>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("contact_copy_updated_at");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("user_profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");
                        });

                    b.OwnsOne("Kart.User.Domain.ValueObjects.Preferences", "Preferences", b1 =>
                        {
                            b1.Property<string>("UserProfileUserId")
                                .HasColumnType("text");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "currency");

                            b1.Property<string>("Locale")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "locale");

                            b1.Property<bool>("MarketingConsent")
                                .HasColumnType("boolean")
                                .HasAnnotation("Relational:JsonPropertyName", "marketingConsent");

                            b1.HasKey("UserProfileUserId");

                            b1.ToTable("user_profiles");

                            b1.ToJson("preferences");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileUserId");

                            b1.OwnsOne("Kart.User.Domain.ValueObjects.NotificationOptIn", "NotificationOptIn", b2 =>
                                {
                                    b2.Property<string>("PreferencesUserProfileUserId")
                                        .HasColumnType("text");

                                    b2.Property<bool>("Email")
                                        .HasColumnType("boolean")
                                        .HasAnnotation("Relational:JsonPropertyName", "email");

                                    b2.Property<bool>("Push")
                                        .HasColumnType("boolean")
                                        .HasAnnotation("Relational:JsonPropertyName", "push");

                                    b2.Property<bool>("Sms")
                                        .HasColumnType("boolean")
                                        .HasAnnotation("Relational:JsonPropertyName", "sms");

                                    b2.HasKey("PreferencesUserProfileUserId");

                                    b2.ToTable("user_profiles");

                                    b2.WithOwner()
                                        .HasForeignKey("PreferencesUserProfileUserId");
                                });

                            b1.Navigation("NotificationOptIn")
                                .IsRequired();
                        });

                    b.Navigation("ContactCopy")
                        .IsRequired();

                    b.Navigation("Preferences")
                        .IsRequired();
                });

            modelBuilder.Entity("Kart.User.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
